[package]
name = "dwsh"
description = "Main interface for dwsh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
relm4.workspace = true
gtk4-layer-shell.workspace = true
gtk4.workspace = true

wayle-core.workspace = true
wayle-media.workspace = true
wayle-battery.workspace = true
wayle-sysinfo.workspace = true
wayle-systray.workspace = true
chrono.workspace = true

anyhow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
